logging:
  level:
    org:
      hibernate:
        sql: debug
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ''
    url: jdbc:mysql://localhost/db_springboot?serverTimezone=America/Bogota&useSSL=false
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      max-file-size:
        10MB
      max-request-size:
        10MB
        