logging:
  level:
    org:
      hibernate:
        sql: debug
spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    password: ''
    url: jdbc:mariadb://localhost:3306/db_springboot?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size:
        10MB
      max-request-size:
        10MB
        